//! Basic example server.
//!
//! This server:
//! - Serves the embedded frontend WASM app
//! - Provides API endpoints for server functions (generated by #[server] macro)
//! - Provides SSE streaming for real-time updates
//! - Provides WebSocket echo endpoint for bidirectional communication
//! - Demonstrates extractor access in server functions (shared state injection)

use axum::Router;
use axum::routing::{get, post};
use axum_egui::sse::{Event, KeepAlive, Sse};
use axum_egui::ws::{WebSocketUpgrade, WebSocketUpgradeExt};
// Import the generated handlers from the frontend crate
use basic_frontend::AppState;
use basic_frontend::api::{add_handler, greet_handler, greet_with_app_handler, whoami_handler};
use futures_util::StreamExt;
use futures_util::stream::{self, Stream};
use rust_embed::RustEmbed;
use std::convert::Infallible;
use std::net::SocketAddr;
use std::time::Duration;

// Embed the frontend assets built by build.rs
// Convention: {CRATE_NAME}_DIST
#[derive(RustEmbed)]
#[folder = "$BASIC_FRONTEND_DIST"]
struct Assets;

/// Handler that serves the app with initial state.
async fn index() -> axum_egui::App<AppState, Assets> {
    axum_egui::App::new(AppState {
        label: "Hello from the server!".into(),
        value: 42.0,
        server_message: None,
    })
}

// ============================================================================
// SSE Handlers
// ============================================================================

/// SSE endpoint that streams a counter every second.
async fn counter_sse() -> Sse<impl Stream<Item = Result<axum::response::sse::Event, Infallible>>> {
    let stream = stream::unfold(0, |count| async move {
        tokio::time::sleep(Duration::from_secs(1)).await;
        let event = Event::new()
            .json_data(count)
            .unwrap_or_else(|_| Event::new().data("error"))
            .into();
        Some((Ok(event), count + 1))
    });

    Sse::new(stream).keep_alive(KeepAlive::default())
}

// ============================================================================
// WebSocket Handlers
// ============================================================================

/// WebSocket echo endpoint that echoes messages back with a prefix.
async fn ws_echo(ws: WebSocketUpgrade) -> impl axum::response::IntoResponse {
    ws.on_upgrade_json(
        |mut socket: axum_egui::ws::JsonWebSocket<String, String>| async move {
            while let Some(Ok(msg)) = socket.next().await {
                let response = format!("Echo: {}", msg);
                if socket.send(response).is_err() {
                    break;
                }
            }
        },
    )
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let app = Router::new()
        .route("/", get(index))
        // API endpoints (handlers generated by #[server] macro)
        .route("/api/add", post(add_handler))
        .route("/api/greet", post(greet_handler))
        .route("/api/whoami", post(whoami_handler))
        // Extractor-enabled endpoint: greet_with_app_handler accepts State<String>
        // because the server function uses #[extract] State(app_name): State<String>
        .route("/api/greet_with_app", post(greet_with_app_handler))
        // SSE endpoint for real-time updates
        .route("/api/sse/counter", get(counter_sse))
        // WebSocket endpoint for bidirectional communication
        .route("/api/ws", get(ws_echo))
        // Serve static assets
        .fallback(axum_egui::static_handler::<Assets>)
        // Provide shared state for extractor-enabled server functions
        .with_state("axum-egui-demo".to_string());

    let addr = SocketAddr::from(([0, 0, 0, 0], 3000));
    println!("Server running on http://{addr}");

    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
