//! Todo app example server.
//!
//! This server demonstrates:
//! - In-memory database (HashMap behind a Mutex)
//! - Token-based authentication via explicit parameters
//! - Multiple CRUD server functions
//! - Server-side initial state injection

use axum::Router;
use axum::routing::{get, post};
// Import the generated handlers from the frontend crate
use rust_embed::RustEmbed;
use std::net::SocketAddr;
use todo_frontend::AppState;
use todo_frontend::api::{
    add_todo_handler, delete_todo_handler, get_todos_handler, login_handler, logout_handler,
    toggle_todo_handler,
};

// Embed the frontend assets built by build.rs
// Convention: {CRATE_NAME}_DIST
#[derive(RustEmbed)]
#[folder = "$TODO_FRONTEND_DIST"]
struct Assets;

/// Handler that serves the app with initial state.
///
/// For unauthenticated users, this provides an empty state.
/// The client will show a login screen.
async fn index() -> axum_egui::App<AppState, Assets> {
    axum_egui::App::new(AppState {
        username: None,
        todos: Vec::new(),
    })
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    // Initialize the global in-memory database
    todo_frontend::api::db::init_db();

    let app = Router::new()
        .route("/", get(index))
        // Auth endpoints
        .route("/api/login", post(login_handler))
        .route("/api/logout", post(logout_handler))
        // Todo CRUD endpoints (handlers generated by #[server] macro)
        .route("/api/get_todos", post(get_todos_handler))
        .route("/api/add_todo", post(add_todo_handler))
        .route("/api/toggle_todo", post(toggle_todo_handler))
        .route("/api/delete_todo", post(delete_todo_handler))
        // Serve static assets
        .fallback(axum_egui::static_handler::<Assets>);

    let addr = SocketAddr::from(([0, 0, 0, 0], 3001));
    println!("Todo app server running on http://{addr}");

    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
